# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ 18 ]
        distro: [ 'temurin' ]
    runs-on: ${{ matrix.os }}


    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java-version }} ${{ matrix.distro }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: ${{ matrix.distro }}
    - name: Build with Maven
      run: mvn verify --file pom.xml
    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files:  ${{ github.workspace }}/target/coverage-reports/jacoco/jacoco.xml
        fail_ci_if_error: false
        verbose: true
